const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderRecipeAccessEmail(payload:any){
 const chef=payload.permission==='chef',role=chef?'Chef':'Kitchen';
 const url='https://thelittlebakerkitchen.com/account.html?next=recipes.html';
 const description=chef?'You can create and edit recipe drafts, costing records and testing logs. Only the owner can approve or publish production recipes.':'You can view production recipes, scale quantities temporarily and check off kitchen steps. Costing, supplier contacts, private notes and testing history stay hidden.';
 const text=`You have ${role} access to the TLB recipe library.\n\n${description}\n\nSign in or create an account using ${String(payload.email||'')} and verify that email address. New invitations expire after 14 days.\n\nOpen recipe library: ${url}\n\nThis gives you recipe access only. It does not grant shop administration access. If this invitation was unexpected, you can ignore it.`;
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Your TLB recipe access</title></head><body style="margin:0;background:#fcf9f1;color:#38271c;font-family:Arial,sans-serif"><table role="presentation" style="width:100%;border-collapse:collapse"><tr><td style="padding:32px 16px"><table role="presentation" style="max-width:600px;width:100%;margin:auto;border:1px solid #dfc9ae;border-radius:12px;background:#fffdf9"><tr><td style="padding:32px"><p style="font-size:12px;letter-spacing:2px">TLB KITCHEN</p><h1 style="font-size:26px">Your recipe library invitation</h1><p>You have <strong>${role}</strong> access.</p><p style="line-height:1.6">${description}</p><p style="line-height:1.6">Sign in or create an account using <strong>${esc(payload.email)}</strong>, then verify that email address. New invitations expire after 14 days.</p><p style="margin:28px 0"><a href="${url}" style="display:inline-block;background:#79502d;color:#fff;padding:14px 20px;border-radius:6px;text-decoration:none">Open recipe library</a></p><p style="font-size:13px;line-height:1.6">Recipe access does not grant access to shop administration. If this invitation was unexpected, you can ignore it.</p></td></tr></table></td></tr></table></body></html>`;
 return {html,text};
}
