import assert from 'node:assert/strict';
import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {makeHarness} from './backend/helpers.mjs';
const require=createRequire((process.env.PGLITE_PACKAGE_ROOT||process.cwd()+'/tests/backend')+'/package.json');
const {PGlite}=require('@electric-sql/pglite'),{pgcrypto}=require('@electric-sql/pglite/contrib/pgcrypto');
export async function setup({fixtures=true}={}){
 const db=new PGlite({extensions:{pgcrypto}});
 await db.exec(await readFile('tests/backend/bootstrap.sql','utf8'));
 for(const f of(await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec((await readFile('supabase/migrations/'+f,'utf8')).replace(/\r\n/g,'\n'));
 if(!fixtures)return {db};
 const h=await makeHarness(db);const api=(user,action,p={})=>h.as(user,async()=>(await db.query('select public.academy_portal_api($1,$2::jsonb) result',[action,JSON.stringify(p)])).rows[0].result);
 const service=(name,args)=>h.as(null,async()=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result,'service_role');
 const secondInstructor=randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values($1,'teacher2@example.test',now(),'{\"full_name\":\"Second Teacher\"}')",[secondInstructor]);await db.query("insert into tlb.staff(user_id,role) values($1,'staff')",[secondInstructor]);h.ids.teacher2=secondInstructor;
 await db.query("update auth.users set raw_user_meta_data=jsonb_build_object('full_name',case id when $1 then 'Alice Baker' when $2 then 'Ben Cupcake' else 'Instructor Test' end) where id in($1,$2,$3)",[h.ids.customer,h.ids.stranger,h.ids.staff]);
 await api(h.ids.owner,'save_instructor',{id:h.ids.staff,display_name:'Chef Cookie'});await api(h.ids.owner,'save_instructor',{id:secondInstructor,display_name:'Chef Cupcake'});
 const cookie=await api(h.ids.owner,'save_class',{name:'Cookies & Brownies',description:'Cookies and brownies from scratch.',instructor_id:h.ids.staff,status:'active',products:['Cookies','Brownies']});
 const cupcake=await api(h.ids.owner,'save_class',{name:'Animal Cupcakes',description:'Learn playful cupcake decoration.',instructor_id:secondInstructor,status:'active',products:['Cupcakes']});
 await api(h.ids.owner,'assign',{class_id:cookie.id,user_ids:[h.ids.customer]});await api(h.ids.owner,'assign',{class_id:cupcake.id,user_ids:[h.ids.stranger]});
 await db.exec('grant select on storage.objects to anon,authenticated;');
 const upload=async(user,p)=>{const m=await api(user,'reserve_media',{...p,size_bytes:42,width:100,height:100});await db.query("insert into storage.objects(bucket_id,name,metadata) values('academy-student-media',$1,'{\"size\":42,\"mimetype\":\"image/webp\"}')",[m.path]);await service('academy_portal_confirm_upload',[m.id,user,'a'.repeat(64)]);return m;};
 const storage=async(user,path)=>h.as(user,async()=>(await db.query("select name from storage.objects where bucket_id='academy-student-media' and name=$1",[path])).rows);
 return {db,h,api,service,cookie,cupcake,upload,storage};
}
export async function run(){const {db,h,api,service,cookie,cupcake,upload,storage}=await setup(),results=[];
 const test=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'ISSUE REMAINS',error:e.message});throw e;}};
 const denied=(user,action,p)=>assert.rejects(api(user,action,p));let privateMedia,galleryMedia,submission,thread,recipe;
 try{
 await test('Anonymous API and gallery gate',async()=>{await denied(null,'dashboard');await denied(null,'gallery');});
 await test('Existing/new account without classes gets global sections and no protected features',async()=>{const d=await api(h.ids.unverified,'dashboard');assert.deepEqual(d.classes,[]);assert.deepEqual(d.gallery,[]);assert.equal(d.academy_newsletter,false);await denied(h.ids.unverified,'class',{id:cookie.id});await denied(h.ids.unverified,'start_thread',{class_id:cookie.id,subject:'No access',body:'Hello'});await denied(h.ids.unverified,'draft_submission',{class_id:cookie.id,title:'No access',visibility:'gallery'});});
 await test('Bulk assignment deduplicates and never opts accounts into newsletters',async()=>{const r=await api(h.ids.owner,'assign',{class_id:cookie.id,user_ids:[h.ids.customer,h.ids.customer]});assert.equal(r.assigned,0);assert.equal((await api(h.ids.customer,'dashboard')).academy_newsletter,false);await denied(h.ids.customer,'assign',{class_id:cupcake.id,user_ids:[h.ids.customer]});});
 await test('Instructor assignment is dynamic and class-scoped',async()=>{assert.equal((await api(h.ids.customer,'class',{id:cookie.id})).instructor,'Chef Cookie');const b=await api(h.ids.staff,'admin_bootstrap');assert.equal(b.owner,false);assert.equal(b.classes.length,1);assert.equal(b.classes[0].id,cookie.id);await denied(h.ids.customer,'admin_bootstrap');await denied(h.ids.staff,'accounts',{query:'Alice'});await denied(h.ids.staff,'class',{id:cupcake.id});});
 await test('Student recipe whitelist and independent production copy',async()=>{const rid=randomUUID(),vid=randomUUID();await db.query("insert into tlb.recipes(id,code,name) values($1,'QA-ACADEMY','QA source')",[rid]);const doc={name:'Vanilla Bake',description:'Student description',private_notes:'SECRET-PRIVATE',critical_notes:'SECRET-CRITICAL',supplier:{secret:'SECRET-SUPPLIER'},variants:[{name:'Main',yield:{quantity:'12',unit:'cookies',cost:'SECRET-YIELD'},groups:[{name:'Dough',ingredients:[{name:'Flour',quantity:'100',unit:'g',brand:'Approved brand',price:999,supplier_id:'SECRET-SUPPLIER'}]}],methods:[{name:'Mix',steps:[{instruction:'Mix gently',internal_notes:'SECRET-METHOD'}]}],equipment:[{name:'Bowl',price:123}],baking:[{name:'Bake',minutes:'15',cost:42}],production_notes:'SECRET-PRODUCTION',additional_costs:[999]}]};await db.query("insert into tlb.recipe_versions(id,recipe_id,number,status,document,cost_snapshot) values($1,$2,1,'production',$3::jsonb,'{\"secret\":999}')",[vid,rid,JSON.stringify(doc)]);recipe=await api(h.ids.owner,'import_recipe',{version_id:vid});assert.ok(!JSON.stringify(recipe.document).includes('SECRET'));assert.ok(!JSON.stringify(recipe.document).includes('price'));await api(h.ids.owner,'assign_recipe',{class_id:cookie.id,recipe_id:recipe.id});await db.query("insert into tlb.recipe_versions(recipe_id,number,status,document) select recipe_id,2,'production',jsonb_set(document,'{description}','\"Changed production\"') from tlb.recipe_versions where id=$1",[vid]);const s=await api(h.ids.customer,'recipe',{class_id:cookie.id,id:recipe.id});assert.equal(s.document.description,'Student description');assert.ok(!JSON.stringify(s).includes(vid));await denied(h.ids.stranger,'recipe',{class_id:cookie.id,id:recipe.id});await denied(h.ids.customer,'recipe',{class_id:cupcake.id,id:recipe.id});await assert.rejects(h.as(h.ids.customer,()=>db.query('select * from tlb.recipe_versions')));});
 await test('Recipe edit creates a version and leaves Production unchanged',async()=>{const r=await api(h.ids.owner,'save_recipe',{id:recipe.id,revision:recipe.revision,title:'Vanilla Bake',document:{...recipe.document,description:'Student edit',student_notes:'Teaching tip'}});assert.equal(r.revision,2);assert.equal((await api(h.ids.owner,'admin_recipe',{id:recipe.id})).versions.length,2);assert.equal((await db.query('select document->>\'description\' d from tlb.recipe_versions where recipe_id=(select recipe_id from tlb.recipe_versions where id=$1) order by number desc limit 1',[recipe.source_version_id])).rows[0].d,'Changed production');});
 await test('Announcement reads are per account; future announcements stay hidden',async()=>{const a=await api(h.ids.owner,'save_announcement',{title:'Welcome bakers',summary:'A new term',content:'Welcome!',status:'published'});await api(h.ids.owner,'save_announcement',{title:'Future',status:'published',publish_at:'2099-01-01T00:00:00Z'});await api(h.ids.customer,'announcement',{id:a.id});const a1=(await api(h.ids.customer,'dashboard')).announcements,a2=(await api(h.ids.stranger,'dashboard')).announcements;assert.equal(a1.length,1);assert.equal(a1[0].read,true);assert.equal(a2[0].read,false);});
 await test('Upcoming workshops accessible without enrollment',async()=>{await api(h.ids.owner,'save_upcoming',{title:'Bread workshop',description:'Coming soon',status:'published',products:['Bread'],inquiry_url:'https://thelittlebakerkitchen.com/contactus.html'});assert.equal((await api(h.ids.unverified,'dashboard')).upcoming.length,1);});
 await test('Submission starts pending; other accounts cannot read media',async()=>{submission=await api(h.ids.customer,'draft_submission',{class_id:cookie.id,title:'Chocolate Chip Cookies',category:'Cookies',caption:'My first batch',visibility:'gallery'});galleryMedia=await upload(h.ids.customer,{purpose:'submission',submission_id:submission.id});await api(h.ids.customer,'submit_work',{id:submission.id});assert.equal((await api(h.ids.stranger,'gallery')).posts.length,0);assert.equal((await storage(h.ids.stranger,galleryMedia.path)).length,0);assert.equal((await storage(h.ids.customer,galleryMedia.path)).length,1);assert.equal((await storage(null,galleryMedia.path)).length,0);await denied(h.ids.stranger,'moderate',{id:submission.id,status:'approved'});await denied(h.ids.teacher2,'moderate',{id:submission.id,status:'approved'});});
 await test('Global mixed-class gallery is visible to all signed-in accounts',async()=>{await api(h.ids.staff,'moderate',{id:submission.id,status:'approved'});const s=await api(h.ids.stranger,'draft_submission',{class_id:cupcake.id,title:'Animal Cupcakes',category:'Cupcakes',visibility:'gallery'});await upload(h.ids.stranger,{purpose:'submission',submission_id:s.id});await api(h.ids.stranger,'submit_work',{id:s.id});await api(h.ids.teacher2,'moderate',{id:s.id,status:'approved'});for(const user of [h.ids.customer,h.ids.stranger,h.ids.unverified]){const g=await api(user,'gallery');assert.equal(g.posts.length,2);assert.equal((await storage(user,galleryMedia.path)).length,1);const text=JSON.stringify(g.posts);assert.ok(!text.includes('@'));assert.ok(!text.includes(h.ids.customer));assert.ok(text.includes('Alice B.'));}assert.equal((await storage(null,galleryMedia.path)).length,0);});
 await test('Private-to-Instructor submissions never become gallery posts',async()=>{const s=await api(h.ids.customer,'draft_submission',{class_id:cookie.id,title:'Please review texture',visibility:'instructor'});privateMedia=await upload(h.ids.customer,{purpose:'submission',submission_id:s.id});await api(h.ids.customer,'submit_work',{id:s.id});await denied(h.ids.owner,'moderate',{id:s.id,status:'approved'});assert.equal((await api(h.ids.customer,'gallery')).posts.length,2);assert.equal((await storage(h.ids.stranger,privateMedia.path)).length,0);assert.equal((await storage(h.ids.staff,privateMedia.path)).length,1);});
 await test('Wrong-class instructor contact and forged class/recipe references fail',async()=>{await denied(h.ids.customer,'start_thread',{class_id:cupcake.id,subject:'Wrong class',body:'Hello'});await denied(h.ids.customer,'draft_submission',{class_id:cookie.id,title:'Wrong recipe',visibility:'gallery',recipe_id:randomUUID()});});
 await test('Question with multiple attachments stays in the correct private thread',async()=>{thread=await api(h.ids.customer,'start_thread',{class_id:cookie.id,subject:'Why did these crack?',body:'Help with my brownies',type:'question'});const first=await upload(h.ids.customer,{purpose:'message',message_id:thread.id});await upload(h.ids.customer,{purpose:'message',message_id:thread.id});await api(h.ids.customer,'send_message',{id:thread.id});assert.equal((await api(h.ids.staff,'thread',{id:thread.thread_id})).messages[0].media.length,2);await denied(h.ids.stranger,'thread',{id:thread.thread_id});await denied(h.ids.teacher2,'thread',{id:thread.thread_id});assert.equal((await storage(h.ids.stranger,first.path)).length,0);assert.equal((await storage(h.ids.staff,first.path)).length,1);const email=(await db.query("select payload from tlb.outbox where event_type='academy_notification' and payload->>'target_id'=$1",[thread.id])).rows[0].payload;assert.equal(email.attachments,true);assert.ok(!JSON.stringify(email).includes(first.path));});
 await test('Instructor replies have participant-specific unread state',async()=>{await api(h.ids.customer,'thread',{id:thread.thread_id});const reply=await api(h.ids.staff,'draft_reply',{id:thread.thread_id,body:'Try a slightly lower oven temperature.'});await api(h.ids.staff,'send_message',{id:reply.id});assert.equal((await api(h.ids.customer,'threads'))[0].unread,1);await api(h.ids.customer,'thread',{id:thread.thread_id});assert.equal((await api(h.ids.customer,'threads'))[0].unread,0);});
 await test('Direct private tables and self-elevation are denied',async()=>{for(const table of ['academy_enrollments','academy_student_recipes','academy_submissions','academy_message_threads','academy_instructors'])await assert.rejects(h.as(h.ids.customer,()=>db.query(`select * from tlb.${table}`)));await denied(h.ids.customer,'save_instructor',{id:h.ids.customer,display_name:'Imposter'});await assert.rejects(h.as(h.ids.customer,()=>db.query("insert into storage.objects(bucket_id,name) values('academy-student-media','forged.webp')")));});
 await test('Revocation blocks classes, recipes, messages, uploads immediately but preserves gallery/history',async()=>{const pending=await api(h.ids.customer,'draft_submission',{class_id:cookie.id,title:'Pending before revoke',visibility:'instructor'});const reserved=await api(h.ids.customer,'reserve_media',{purpose:'submission',submission_id:pending.id,size_bytes:42,width:100,height:100});const a=await api(h.ids.owner,'account',{id:h.ids.customer});await api(h.ids.owner,'revoke',{id:a.enrollments[0].id});await denied(h.ids.customer,'class',{id:cookie.id});await denied(h.ids.customer,'recipe',{class_id:cookie.id,id:recipe.id});await denied(h.ids.customer,'thread',{id:thread.thread_id});await denied(h.ids.customer,'submit_work',{id:pending.id});await assert.rejects(h.as(h.ids.customer,()=>db.query('select public.academy_portal_upload_check($1)',[reserved.id])));assert.equal((await storage(h.ids.customer,privateMedia.path)).length,0);assert.equal((await api(h.ids.customer,'gallery')).posts.length,2);const history=(await api(h.ids.owner,'account',{id:h.ids.customer})).enrollments;assert.equal(history[0].status,'revoked');assert.ok(history[0].removed_by);await api(h.ids.owner,'assign',{class_id:cookie.id,user_ids:[h.ids.customer]});assert.equal((await api(h.ids.owner,'account',{id:h.ids.customer})).enrollments.length,2);});
 await test('Independent Academy consent and marketing recipient suppression',async()=>{await api(h.ids.customer,'newsletter',{academy:true});await db.exec("update tlb.settings set data=jsonb_set(data,'{pickup_address}','\"QA Bakery address\"') where id");const payload={kind:'marketing',audience:'students',subject:'New classes',body:'Join the next workshop.'};assert.equal((await api(h.ids.owner,'broadcast_preview',payload)).recipients,1);const b=await api(h.ids.owner,'broadcast_send',{...payload,idempotency_key:randomUUID()});assert.equal(b.recipients,1);await api(h.ids.customer,'newsletter',{academy:false});const o=(await db.query("select * from tlb.outbox where payload->>'broadcast_id'=$1",[b.id])).rows[0];const lease=randomUUID();await db.query("update tlb.outbox set status='sending',lease_token=$2,leased_until=now()+interval '5 minutes' where id=$1",[o.id,lease]);assert.equal((await h.service('prepare_email',{id:o.id,lease_token:lease})).skip,true);assert.equal((await db.query("select count(*) n from tlb.newsletter_subscribers where email='customer@example.test'")).rows[0].n,0);});
 await test('Owner backup snapshot contains Academy metadata, excludes secrets and image bytes',async()=>{const start=await service('academy_backup_service',['begin',{kind:'download',user_id:h.ids.owner}]);assert.equal(start.file_count,0);assert.ok(start.tables.includes('academy_student_recipe_versions'));const p=await service('academy_backup_service',['page',{job_id:start.job_id,lease_token:start.lease_token,table:'academy_newsletter_preferences'}]);assert.ok(p.rows.length);assert.ok(!JSON.stringify(p).includes('unsubscribe_token'));await assert.rejects(h.as(h.ids.staff,()=>db.query("select public.academy_backup_api('status','{}')")));await service('academy_backup_service',['finish',{job_id:start.job_id,lease_token:start.lease_token,sha256:'a'.repeat(64),size_bytes:200}]);});
 await test('All new tables have RLS and no direct customer grants',async()=>{const tables=(await db.query("select c.relname,c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='tlb' and c.relkind='r' and c.relname like 'academy_%'")).rows;assert.ok(tables.length>20);assert.ok(tables.every(t=>t.relrowsecurity));});
 }finally{await mkdir('tests/artifacts/academy-portal',{recursive:true});await writeFile('tests/artifacts/academy-portal/backend-results.json',JSON.stringify(results,null,2));await db.close();}
}
if(fileURLToPath(import.meta.url)===resolve(process.argv[1]||''))await run().catch(e=>{console.error('FAIL',e.message,e.where||'');process.exitCode=1;});
