import {createRequire} from 'node:module';import {join,resolve} from 'node:path';import {mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'package.json')),{chromium}=require('playwright');
const base='http://127.0.0.1:4176',out=resolve('test-results/academy');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const api=(action,payload={})=>page.evaluate(async({action,payload})=>{const r=await fetch('/__preview/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'academy:'+action,payload})});const data=await r.json();if(!r.ok)throw Error(data.error);return data;},{action,payload});
await page.goto(base+'/__preview/owner',{waitUntil:'domcontentloaded'});await page.locator('[data-ac=edit]').first().waitFor();
const initial=await api('admin'),camp=initial.classes.find(c=>c.draft.slug==='2nd-summer-baking-camp');
await page.locator(`[data-ac=edit][data-id="${camp.id}"]`).click();await page.locator('[data-ac-field=title]').fill('2nd Summer Baking Camp');
const placeholderToggle=page.locator('input[type=checkbox][data-ac-field=allow_photo_placeholders]');assert.equal(await placeholderToggle.count(),1);await placeholderToggle.check();
await page.locator('[data-ac=media][data-path=thumbnail]').click();
const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=600;const x=c.getContext('2d');x.fillStyle='#efc3b4';x.fillRect(0,0,800,600);x.fillStyle='#302623';x.font='40px Georgia';x.fillText('Academy test image',200,300);return c.toDataURL('image/png').split(',')[1];});
await page.locator('dialog input[type=file]').setInputFiles({name:'academy-test.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.locator('dialog.ac-media-dialog').waitFor({state:'detached'});
assert.equal(await page.locator('[data-ac-field="thumbnail.alt"]').count(),1);
await page.locator('[data-ac=media][data-path=hero]').click();await page.locator('dialog [data-asset]').first().click();await page.locator('[data-ac-field="hero.caption"]').fill('Test fixture · not a verified class photo');
await page.locator('[data-ac=save]').click();await page.locator('[data-ac-status]').filter({hasText:'Class draft saved'}).waitFor();
let data=await api('admin'),saved=data.classes.find(c=>c.id===camp.id);assert.ok(saved.draft.hero.asset_id);assert.equal(data.assets[0].storage_path.endsWith('.webp'),true);assert.equal(saved.draft.allow_photo_placeholders,true);
await placeholderToggle.uncheck();await page.locator('[data-ac=save]').click();await page.locator('[data-ac-status]').filter({hasText:'Class draft saved'}).waitFor();data=await api('admin');saved=data.classes.find(c=>c.id===camp.id);assert.equal(saved.draft.allow_photo_placeholders,false);
assert.equal((await page.request.get(base+'/__preview/photo/'+data.assets[0].storage_path)).headers()['content-type'],'image/webp');
const batch1=crypto.randomUUID(),batch2=crypto.randomUUID(),creation=crypto.randomUUID();
const ref={...saved.draft.hero,caption:'Sample photo caption',alt:'Academy QA image',focal_x:30,focal_y:65};
for(const row of data.classes){const content={...row.draft,thumbnail:ref,hero:ref,description:'QA class description',module_description:'QA recipe lineup',category_label:'Baking class',creations:[{id:creation,name:'QA creation',description:'Finished creation description',photos:[{...ref,batch_id:batch1}]}],batches:[{id:batch1,label:'Session One',description:'First batch',student_count:null,start_date:'',end_date:'',cover:ref,photos:[ref,{...ref,caption:'Second photo'}]},{id:batch2,label:'Session Two',description:'Second batch',student_count:8,start_date:'',end_date:'',cover:ref,photos:[{...ref,caption:'Other batch photo'}]}],videos:[{id:crypto.randomUUID(),url:'https://www.instagram.com/reel/TEST_QA_ONLY/',title:'Sample video',batch_id:'',cover:null}]};let r=await api('save_class',{id:row.id,revision:row.revision,content});await api('publish_class',{id:r.id,revision:r.revision});}
await api('publish_settings',{revision:data.settings.revision});
const pub=await browser.newContext({viewport:{width:1440,height:1000}}),view=await pub.newPage();view.on('pageerror',e=>errors.push(e.message));
const placeholderId=crypto.randomUUID(),placeholderSlug='placeholder-'+placeholderId;let placeholderRow=await api('save_class',{id:placeholderId,revision:0,content:{...saved.draft,title:'Placeholder QA class',slug:placeholderSlug,allow_photo_placeholders:true,thumbnail:null,hero:null,description:'',module_description:'',achievement:'',student_total:null,creations:[],batches:[],videos:[]}});placeholderRow=await api('publish_class',{id:placeholderId,revision:placeholderRow.revision});
await view.goto(base+'/academy.html?class='+placeholderSlug,{waitUntil:'domcontentloaded'});await view.locator('.academy-hero .academy-placeholder').waitFor();assert.ok((await view.locator('.academy-hero').innerText()).includes('Photo to be added'));assert.equal(await view.locator('#student-creations,#class-albums,#bakers-in-action').count(),0);assert.equal(await view.locator('.academy-class-list [aria-current=page] .academy-placeholder').count(),1);await api('delete_class',{id:placeholderId,revision:placeholderRow.revision});
await view.goto(base+'/academy.html',{waitUntil:'domcontentloaded'});await view.locator('.academy-class-heading h1').waitFor();
assert.equal(await view.locator('.academy-class-heading h1').innerText(),'2nd Summer Baking Camp');assert.equal(await view.locator('.academy-class-list a').first().getAttribute('aria-current'),'page');
assert.equal(await view.locator('#mainNav a[href="academy.html"]').count(),1);assert.equal(await view.locator('#mainNav a[href="blogs.html"]').count(),0);assert.equal(await view.locator('#mainNav a[href="academy.html"]').getAttribute('aria-current'),'page');assert.ok((await view.locator('.academy-class-heading h1').evaluate(el=>getComputedStyle(el).fontFamily)).includes('Lobster'));
assert.deepEqual(await view.locator('.academy-content h2').allTextContents(),['Inside the class','Look what we made','Explore the albums','Our bakers in action','Class videos','Your next sweet adventure?']);
await view.locator('[data-academy-class="cookies-and-brownies"]').click();await view.waitForURL('**?class=cookies-and-brownies');await view.reload({waitUntil:'domcontentloaded'});await view.locator('.academy-class-heading h1').filter({hasText:'Cookies & Brownies'}).waitFor();
await view.goBack({waitUntil:'domcontentloaded'});await view.locator('.academy-class-heading h1').filter({hasText:'2nd Summer'}).waitFor();await view.goForward({waitUntil:'domcontentloaded'});await view.locator('.academy-class-heading h1').filter({hasText:'Cookies & Brownies'}).waitFor();
await view.locator(`[data-academy-batch="${batch2}"]`).click();await view.locator('.academy-active-batch h3').filter({hasText:'Session Two'}).waitFor();assert.ok(view.url().includes('batch='));assert.equal(await view.locator('#student-creations .academy-photo-open').count(),1);assert.equal(await view.locator('#bakers-in-action .academy-photo-open').count(),1);
await view.locator('#student-creations .academy-photo-open').click();assert.equal(await view.locator('.academy-lightbox').evaluate(el=>el.open),true);await view.keyboard.press('Escape');assert.equal(await view.locator('.academy-lightbox').evaluate(el=>el.open),false);
await view.route('https://www.instagram.com/embed.js',r=>r.abort());await view.locator('[data-instagram-load]').click();await view.locator('[data-instagram-status]').filter({hasText:'could not load'}).waitFor();assert.equal(await view.locator('a[href="https://www.instagram.com/reel/TEST_QA_ONLY/"]').last().isVisible(),true);
for(const width of [1440,768,390,320]){
 await view.setViewportSize({width,height:1000});
 await view.waitForFunction(width=>document.querySelector('.academy-picker')?.open===(width>=900),width);
 assert.equal(await view.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'overflow '+width);
 if(width<900){await view.locator('.academy-picker summary').click();assert.equal(await view.locator('.academy-class-list a').last().isVisible(),true);await view.locator('.academy-picker summary').click();}
 const photoSizes=await view.locator('.academy-hero>.academy-photo,.academy-album>div>img').evaluateAll(images=>images.map(img=>{const r=img.getBoundingClientRect(),s=getComputedStyle(img),ratio=s.aspectRatio.split('/').map(Number);return {height:r.height,expected:Math.min(r.width/(ratio[0]/(ratio[1]||1)),Number.parseFloat(s.maxHeight)||Infinity)};}));
 assert.ok(photoSizes.every(p=>Math.abs(p.height-p.expected)<=2),'Photo aspect ratios at '+width);
 await view.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await view.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 await view.screenshot({path:join(out,`album-browser-${width}.png`),fullPage:true});
}
assert.deepEqual(errors,[]);await browser.close();console.log('PASS owner PNG→WebP upload, reuse, boolean placeholder option and public placeholder rendering; Academy header replaces Blogs; published class URLs/back/forward, batches, lightbox, Instagram fallback, 1440/768/390/320px.');
