import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,join,extname,sep} from 'node:path';
const require=createRequire(import.meta.url),{chromium}=require(join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'playwright'));
const root=resolve(import.meta.dirname,'../..'),origin='https://newsletter-admin.test',out=join(root,'test-results/newsletter-manager');await mkdir(out,{recursive:true});
const offer={enabled:true,kind:'percent',value:5,min_subtotal_cents:30000,cap_cents:10000,valid_days:30,expires_at:null,revision:1};
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH});
const mock=`let state={offer:${JSON.stringify(offer)},subscriber_count:42,campaigns:[]};window.calls=[];export async function newsletterAdmin(action,p={}){window.calls.push({action,payload:structuredClone(p)});if(action==='load')return structuredClone(state);if(action==='save_offer'){state.offer={...p.offer,revision:2};return state.offer}if(action==='save'){const c={...p,status:'draft',revision:p.revision+1};state.campaigns=[c];return structuredClone(c)}if(action==='test')return {queued:1,email:'owner@example.test'};if(action==='queue')return {...state.campaigns[0],status:'queued',queued:42,delivery_method:'broadcast',broadcast_status:'pending'};throw Error('Unexpected action '+action)}`;
const html=`<html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/ordering/ordering.css"><link rel="stylesheet" href="/assets/ordering/manage.css"><link rel="stylesheet" href="/assets/ordering/accounting.css"><link rel="stylesheet" href="/assets/ordering/newsletter-manager.css"><body class="manage-page"><main style="padding:20px;max-width:1400px;margin:auto"><div id="offers"></div><div id="newsletters"></div></main><script type="module">import {mountNewsletters,mountWelcomeOffer} from '/assets/ordering/newsletter-manager.js';mountWelcomeOffer(document.querySelector('#offers'));mountNewsletters(document.querySelector('#newsletters'),{settings:{pickup_address:'Test shop address'},products:[{id:'p1',name:'Chocolate cake',image_url:'https://newsletter-admin.test/photo.svg'}]});</script></body></html>`;
try{for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{errors.push('Unexpected native dialog');d.dismiss()});
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname.includes('newsletter-admin-client.js'))return route.fulfill({contentType:'text/javascript',body:mock});if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:html});if(u.hostname!==new URL(origin).hostname||u.pathname==='/photo.svg')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="800" height="500" fill="#efcdbc"/></svg>'});const path=resolve(root,'.'+u.pathname);if(!path.startsWith(root+sep))return route.abort();try{let body=await readFile(path);return route.fulfill({body,contentType:{'.js':'text/javascript','.css':'text/css','.png':'image/png'}[extname(path)]||'application/octet-stream'})}catch{return route.fulfill({status:404,body:''})}});

 await page.goto(origin);await page.locator('#offers [name=value]').fill('12');await page.locator('#offers [name=valid_days]').fill('14');await page.getByRole('button',{name:'Save welcome offer',exact:true}).click();await page.getByText('Welcome offer saved.',{exact:false}).waitFor();assert.equal(await page.locator('#offers [name=value]').inputValue(),'12');assert.equal((await page.evaluate(()=>window.calls.find(c=>c.action==='save_offer'))).payload.offer.valid_days,14);
 assert.equal(await page.locator('.nl-template-card').count(),3);await page.locator('[data-template=showcase]').click();await page.locator('[name=subject]').fill('Our latest treats');await page.locator('[name=title]').fill('Something sweet');await page.locator('[data-nl-hero]').selectOption('p1');assert.equal(await page.locator('[name=subject]').inputValue(),'Our latest treats','Product selection retains edits');
 await page.locator('[name=template]').selectOption('offer');await page.locator('[name=offer_heading]').evaluate(el=>el.closest('details').open=true);await page.locator('[name=offer_heading]').fill('10% OFF');await page.locator('[name=offer_terms]').fill('Sample terms for testing only');
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByText('Newsletter draft saved.',{exact:true}).waitFor();assert.equal((await page.evaluate(()=>window.calls.filter(c=>c.action==='save').at(-1))).payload.content.offer_heading,'10% OFF');
 await page.locator('[data-nl=test]').click();await page.getByText('Test queued for owner@example.test.',{exact:false}).waitFor();assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.action==='queue').length),0,'Test does not send a campaign');
 await page.locator('[data-nl=send]').click();const dialog=page.getByRole('dialog',{name:'Send this newsletter?'});await dialog.getByRole('button',{name:'Keep editing'}).click();assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.action==='queue').length),0,'Cancelling does not send');
 await page.locator('iframe').scrollIntoViewIfNeeded();await page.screenshot({path:join(out,`composer-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'Composer fits viewport');
 await page.locator('[data-nl=send]').focus();await page.keyboard.press('Enter');await dialog.getByRole('button',{name:'Send to subscribers',exact:true}).click();await page.getByText('Resend Broadcast queued.',{exact:false}).waitFor();assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.action==='queue').length),1);assert.equal(await page.locator('[name=subject]').isDisabled(),true);assert.deepEqual(errors,[]);await context.close();console.log('PASS newsletter offer controls, responsive composer, templates, preview, test-only send and final-send confirmation at '+width+'px');
}}finally{await browser.close()}
