// Browser fixtures only. No production requests or writes.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,mkdir} from 'node:fs/promises';
import {join,resolve,extname} from 'node:path';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PACKAGE_ROOT?join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'playwright'):'playwright');
const root=resolve(import.meta.dirname,'../..'),origin='https://packages.test',out=join(root,'test-results/package-tools');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH||undefined});
const mime={'.js':'text/javascript','.css':'text/css','.woff2':'font/woff2'};
try{for(const width of [1440,390,320]){
 const ctx=await browser.newContext({viewport:{width,height:950},hasTouch:width<500});await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:'<html><head><link rel="stylesheet" href="/assets/ordering/ordering.css"><link rel="stylesheet" href="/assets/ordering/manage.css"><link rel="stylesheet" href="/assets/ordering/party-packages.css"><link rel="stylesheet" href="/assets/ordering/catalog-order.css"><link rel="stylesheet" href="/assets/ordering/site-dialog.css"></head><body class="manage-page"><main style="max-width:1100px;margin:auto;padding:12px"><div id="manager"></div></main></body></html>'});try{return route.fulfill({contentType:mime[extname(u.pathname)]||'application/octet-stream',body:await readFile(join(root,u.pathname))})}catch{return route.fulfill({status:404,body:'Missing'})}});
 const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);
 await page.evaluate(async()=>{const {mountPartyPackageManager}=await import('/assets/ordering/party-package-manager.js');window.fixture={items:[1,2,3].map(i=>({id:'p'+i,name:'Package '+i,subtitle:'Treats',features:[{label:'Choose flavors',detail:'Vanilla & chocolate'}],price_cents:900000,badge:'New',published:true,sort_order:i*10,revision:1,created_at:'2026-09-01'})),calls:[],fail:false,gate:false};const f=window.fixture;
  mountPartyPackageManager(document.querySelector('#manager'),{role:'owner',connected:true,page:'party',cartApi:async()=>({items:[],revision:1}),api:async(action,payload)=>{f.calls.push({action,payload});if(action==='admin_list')return structuredClone({items:f.items,settings:{inclusions:[{label:'Setup',detail:''}],revision:1}});if(action==='reorder'){if(f.gate)await new Promise(r=>{f.release=r});if(f.fail){f.fail=false;throw Error('Packages changed in another window. Refresh before rearranging.')}f.items=payload.ids.map((id,i)=>({...f.items.find(p=>p.id===id),sort_order:i+1,revision:2}));return structuredClone({items:f.items})}if(action==='save'){const p={...payload.package,revision:1,created_at:'2026-09-29'};f.items.push(p);return structuredClone(p)}throw Error('Unexpected action '+action)}});
 });
 await page.locator('[data-party-duplicate="p1"]').waitFor();
 const names=()=>page.locator('[data-party-list] h2').allTextContents();
 const drag=async(from,to,touch=false,cancel=false)=>{await page.locator(`[data-order-handle="${from}"]`).scrollIntoViewIfNeeded();const a=await page.locator(`[data-order-handle="${from}"]`).boundingBox(),b=await page.locator(`[data-order-item="${to}"]`).boundingBox();const start={x:a.x+a.width/2,y:a.y+a.height/2},end={x:b.x+b.width/2,y:b.y+b.height/2};if(touch){const cdp=await ctx.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/12,y:start.y+(end.y-start.y)*i/12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach()}else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:12});if(cancel)await page.keyboard.press('Escape');await page.mouse.up()}};
 await drag(0,1,width<500);await page.getByText('Package order saved.',{exact:true}).waitFor();assert.deepEqual(await names(),['Package 2','Package 1','Package 3']);
 await page.locator('[data-order-handle="1"]').press('ArrowUp');await page.waitForFunction(()=>document.querySelector('[data-party-list] h2').textContent==='Package 1'&&document.querySelector('#manager').dataset.busy==='false');
 await drag(0,1,false,true);assert.deepEqual(await names(),['Package 1','Package 2','Package 3']);assert.equal(await page.locator('.catalog-order-ghost').count(),0);
 await page.evaluate(()=>fixture.fail=true);await page.locator('[data-order-handle="0"]').press('ArrowDown');await page.locator('[data-party-message]').filter({hasText:'changed in another window'}).waitFor();assert.deepEqual(await names(),['Package 1','Package 2','Package 3']);
 await page.evaluate(()=>fixture.gate=true);await page.locator('[data-order-handle="0"]').press('ArrowDown');await page.waitForFunction(()=>!!fixture.release);assert.equal(await page.locator('[data-party-new]').isDisabled(),true);await page.evaluate(()=>{fixture.gate=false;fixture.release()});await page.waitForFunction(()=>document.querySelector('#manager').dataset.busy==='false');
 await page.locator('[data-party-duplicate="p1"]').click();assert.equal(await page.locator('[name="name"]').inputValue(),'Package 1 (copy)');assert.equal(await page.locator('[name="price"]').inputValue(),'9000.00');assert.equal(await page.locator('[data-feature-detail]').inputValue(),'Vanilla & chocolate');assert.equal(await page.locator('[name="published"]').isChecked(),false);assert.equal(await page.evaluate(()=>fixture.items.length),3);
 await page.locator('[name="name"]').fill('Editable copy');await page.locator('[data-feature-label]').fill('More treats');await page.locator('[data-party-form] button[type=submit]').click();await page.locator('.party-editor').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>fixture.items.length),4);assert.equal(await page.evaluate(()=>fixture.items.find(p=>p.id==='p1').features[0].label),'Choose flavors');assert.notEqual(await page.evaluate(()=>fixture.items.find(p=>p.name==='Editable copy').id),'p1');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:join(out,'package-tools-'+width+'.png'),fullPage:true});assert.deepEqual(errors,[]);await ctx.close();console.log('PASS package mouse/touch/keyboard reorder, escape, failure rollback, busy state and independent hidden duplicate at '+width+'px');
}}finally{await browser.close()}
