"""Generate public portfolio thumbnails from an explicit JSON list of photo URLs.

Usage: python scripts/gallery-thumbnails.py /path/to/gallery-urls.json
Requires Pillow. Originals are read only; no customer uploads or remote downloads.
"""
import hashlib
import json
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'assets/img/gallery-thumbnails'
OUTPUT.mkdir(parents=True, exist_ok=True)
mapping, stats = {}, {'original_bytes': 0, 'thumbnail_bytes': 0, 'photos': 0}
for url in sorted(set(json.loads(Path(sys.argv[1]).read_text(encoding='utf-8-sig')))):
    parsed = urlsplit(url)
    if parsed.scheme != 'https' or parsed.netloc != 'thelittlebakerkitchen.com':
        raise ValueError('Only existing public website assets may be processed')
    path = unquote(parsed.path)
    source = (ROOT / path.lstrip('/')).resolve()
    if not source.is_relative_to(ROOT / 'assets') or not source.is_file():
        raise ValueError(f'Not a local public asset: {path}')
    name = hashlib.sha256(path.encode()).hexdigest()[:20] + '.webp'
    target = OUTPUT / name
    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original)
        image.thumbnail((640, 640), Image.Resampling.LANCZOS)
        image.convert('RGBA' if 'A' in image.getbands() else 'RGB').save(target, 'WEBP', quality=78, method=6)
    if target.stat().st_size >= source.stat().st_size:
        target.unlink()  # Only the thumbnail just generated in OUTPUT.
        continue
    mapping[path] = '/assets/img/gallery-thumbnails/' + name
    if source.suffix.lower() != '.webp' and source.with_suffix('.webp').is_file():
        mapping[str(Path(path).with_suffix('.webp')).replace('\\', '/')] = mapping[path]
    stats['original_bytes'] += source.stat().st_size
    stats['thumbnail_bytes'] += target.stat().st_size
    stats['photos'] += 1

(ROOT / 'assets/ordering/gallery-thumbnail-map.js').write_text(
    '// Generated by scripts/gallery-thumbnails.py; original photos remain unchanged.\n'
    + 'export const galleryThumbnails = ' + json.dumps(mapping, ensure_ascii=True, separators=(',', ':')) + ';\n', encoding='utf8')
print(json.dumps(stats))
